ServerEvents.recipes(event => {
    let id = (recipe) => {
        event.remove({id: recipe})
    }
    id('create:compat/silentsgems/crushing/agate_ore')
    id('create:compat/silentsgems/crushing/amber_ore')
    id('create:compat/silentsgems/crushing/amethyst_ore')
    id('create:compat/silentsgems/crushing/ametrine_ore')
    id('create:compat/silentsgems/crushing/apatite_ore')
    id('create:compat/silentsgems/crushing/aquamarine_ore')
    id('create:compat/silentsgems/crushing/benitoite_ore')
    id('create:compat/silentsgems/crushing/cats_eye_ore')
    id('create:compat/silentsgems/crushing/chrysoprase_ore')
    id('create:compat/silentsgems/crushing/coral_ore')
    id('create:compat/silentsgems/crushing/euclase_ore')
    id('create:compat/silentsgems/crushing/fluorite_ore')
    id('create:compat/silentsgems/crushing/garnet_ore')
    id('create:compat/silentsgems/crushing/green_sapphire_ore')
    id('create:compat/silentsgems/crushing/jade_ore')
    id('create:compat/silentsgems/crushing/jasper_ore')
    id('create:compat/silentsgems/crushing/kunzite_ore')
    id('create:compat/silentsgems/crushing/lepidolite_ore')
    id('create:compat/silentsgems/crushing/malachite_ore')
    id('create:compat/silentsgems/crushing/moonstone_ore')
    id('create:compat/silentsgems/crushing/morganite_ore')
    id('create:compat/silentsgems/crushing/onyx_ore')
    id('create:compat/silentsgems/crushing/opal_ore')
    id('create:compat/silentsgems/crushing/pearl_ore')
    id('create:compat/silentsgems/crushing/phosphophyllite_ore')
    id('create:compat/silentsgems/crushing/pyrope_ore')
    id('create:compat/silentsgems/crushing/sodalite_ore')
    id('create:compat/silentsgems/crushing/spinel_ore')
    id('create:compat/silentsgems/crushing/sunstone_ore')
    id('create:compat/silentsgems/crushing/tanzanite_ore')
    id('create:compat/silentsgems/crushing/tektite_ore')
    id('create:compat/silentsgems/crushing/yellow_diamond_ore')
    id('create:compat/silentsgems/crushing/zircon_ore')
    id('unusualend:chiseled_endstone_recipe_1')

    event.remove({output: 'mekanism:digital_miner'})
})