//priority: 1

ServerEvents.tags('item', event => {

    event.remove('forge:ores/silver', 'silentgems:raw_silver')
    event.add('forge:raw_materials/silver', 'silentgems:raw_silver')
    event.add('minecraft:redstone_ores', 'byg:cryptic_redstone_ore')

    for(const core of core_type) {
        event.add('randomium:blacklist', `kubejs:unprocessed_${core}_core`)
        event.add('randomium:blacklist', `kubejs:refined_${core}_core`)
    }

    event.add('ae2:can_remove_color', 'supplementaries:soap')

    event.add('dar:no_emc', '#forge:berries')
    event.add('dar:no_emc', '#forge:cobblestone')
    event.add('dar:no_emc', '#forge:crops')
    event.add('dar:no_emc', '#forge:dusts')
    event.add('dar:no_emc', '#forge:eggs')
    event.add('dar:no_emc', '#forge:foods')
    event.add('dar:no_emc', '#forge:gems')
    event.add('dar:no_emc', '#forge:heads')
    event.add('dar:no_emc', '#forge:honeycombs')
    event.add('dar:no_emc', '#forge:ingots')
    event.add('dar:no_emc', '#forge:nether_stars')
    event.add('dar:no_emc', '#forge:netherrack')
    event.add('dar:no_emc', '#forge:nuggets')
    event.add('dar:no_emc', '#forge:pumpkins')
    event.add('dar:no_emc', '#forge:raw_fishes')
    event.add('dar:no_emc', '#forge:rods')
    event.add('dar:no_emc', '#forge:seeds')
    event.add('dar:no_emc', '#minecraft:dirt')
    event.add('dar:no_emc', '#minecraft:flowers')
    event.add('dar:no_emc', '#minecraft:logs')
    event.add('dar:no_emc', '#minecraft:music_discs')
    event.add('dar:no_emc', '#minecraft:planks')
    event.add('dar:no_emc', '#minecraft:sand')
    event.add('dar:no_emc', '#minecraft:saplings')
    event.add('dar:no_emc', '#minecraft:soul_fire_base_blocks')
    event.add('dar:no_emc', '#minecraft:wool')
    event.add('dar:no_emc', 'basalt')
    event.add('dar:no_emc', 'chorus_fruit')
    event.add('dar:no_emc', 'clay_ball')
    event.add('dar:no_emc', 'disc_fragment_5')
    event.add('dar:no_emc', 'echo_shard')
    event.add('dar:no_emc', 'feather')
    event.add('dar:no_emc', 'ghast_tear')
    event.add('dar:no_emc', 'goat_horn')
    event.add('dar:no_emc', 'honey_bottle')
    event.add('dar:no_emc', 'name_tag')
    event.add('dar:no_emc', 'netherite_scrap')
    event.add('dar:no_emc', 'obsidian')
    event.add('dar:no_emc', 'phantom_membrane')
    event.add('dar:no_emc', 'poisonous_potato')
    event.add('dar:no_emc', 'rabbit_foot')
    event.add('dar:no_emc', 'scute')
    event.add('dar:no_emc', 'shulker_shell')
    event.add('dar:no_emc', 'spider_eye')
    event.add('dar:no_emc', 'string')

    event.add('dar:emc', '#forge:ores')
    event.add('dar:emc', '#forge:raw_materials')

    event.add('randomium:blacklist', /ae2/)
    event.add('randomium:blacklist', /allthemodium/)
    event.add('randomium:blacklist', /appbot/)
    event.add('randomium:blacklist', /appmek/)
    event.add('randomium:blacklist', /cfm/)
    event.add('randomium:blacklist', /chipped/)
    event.add('randomium:blacklist', /creative/)
    event.add('randomium:blacklist', /encased_cogwheel/)
    event.add('randomium:blacklist', /encased_large_cogwheel/)
    event.add('randomium:blacklist', /encased_shaft/)
    event.add('randomium:blacklist', /everycomp/)
    event.add('randomium:blacklist', /factory/)
    event.add('randomium:blacklist', /incomplete/)
    event.add('randomium:blacklist', /infinity/)
    event.add('randomium:blacklist', /installer/)
    event.add('randomium:blacklist', /lootr/)
    event.add('randomium:blacklist', /mcw/)
    event.add('randomium:blacklist', /megacells/)
    event.add('randomium:blacklist', /netherite/)
    event.add('randomium:blacklist', /projecte/)
    event.add('randomium:blacklist', /unfinished/)
    event.add('randomium:blacklist', /tetra:modular/)
    event.add('randomium:blacklist', /thermal_extra/)
    event.add('randomium:blacklist', /shulker_box/)
    event.add('randomium:blacklist', /silentgear/)
    event.add('randomium:blacklist', '#forge:coins')
    event.add('randomium:blacklist', '#silentgems:glowroses')
    event.add('randomium:blacklist', 'mekanism:atomic_disassembler')
    event.add('randomium:blacklist', 'create:handheld_worldshaper')
    event.add('randomium:blacklist', 'createaddition:digital_adapter')
    event.add('randomium:blacklist', 'touhou_little_maid:substitute_jizo')
    event.remove('randomium:blacklist', '#forge:ores')
    event.remove('randomium:blacklist', '#forge:raw_materials')

    event.add('forge:storage_blocks/silver', 'silentgems:silver_block')
    event.add('forge:storage_blocks/flint', 'supplementaries:flint_block')
    event.add('forge:storage_block/apple', 'thermal:apple_block')
    event.add('forge:storage_block/carrot', 'thermal:carrot_block')
    event.add('forge:storage_block/carrot', 'farmersdelight:carrot_crate')
    event.add('forge:storage_block/potato', 'thermal:potato_block')
    event.add('forge:storage_block/potato', 'farmersdelight:potato_crate')
    event.add('forge:storage_block/beetroot', 'thermal:beetroot_block')
    event.add('forge:storage_block/beetroot', 'farmersdelight:beetroot_crate')
    event.add('forge:storage_block/raw_naquadah', 'sgjourney:raw_naquadah_block')
    event.add('forge:storage_block', '#forge:storage_blocks/raw_crimson_iron')
    event.add('forge:storage_block', '#forge:storage_blocks/raw_azure_silver')
    event.add('forge:storage_block', '#forge:storage_block/raw_naquadah')
    event.add('forge:storage_block', '#forge:storage_blocks/flint')

    event.add('forge:mushrooms', 'monsters_and_girls:end_puffball')
    event.add('forge:mushrooms', 'monsters_and_girls:ink_cap_mushroom')
    event.add('forge:mushrooms', 'monsters_and_girls:molten_fungus')
    event.add('forge:mushrooms', 'monsters_and_girls:soul_wanderer_mushroom')

    event.add('minecraft:small_flowers', 'culturaldelights:wild_corn')
    event.add('minecraft:small_flowers', 'culturaldelights:wild_cucumbers')
    event.add('minecraft:small_flowers', 'culturaldelights:wild_eggplants')
    event.add('minecraft:small_flowers', 'farmersrespite:wild_coffee_bush')
    event.add('minecraft:small_flowers', 'farmersrespite:wild_tea_bush')

    event.add('farmersdelight:wild_crop', 'culturaldelights:wild_corn')
    event.add('farmersdelight:wild_crop', 'culturaldelights:wild_cucumbers')
    event.add('farmersdelight:wild_crop', 'culturaldelights:wild_eggplants')
    event.add('farmersdelight:wild_crop', 'farmersrespite:wild_tea_bush')
    event.add('farmersdelight:wild_crop', 'farmersrespite:wild_coffee_bush')

    event.add('forge:ores/quartz', 'byg:blue_nether_quartz_ore')
    event.add('forge:ores/quartz', 'byg:brimstone_nether_quartz_ore')
    event.add('forge:ores/redstone', 'byg:cryptic_redstone_ore')
    
    event.add('forge:ingots/bronze', 'create_dd:bronze_ingot')
    event.add('forge:plates/bronze', 'create_dd:bronze_sheet')
    event.add('forge:nuggets/bronze', 'create_dd:bronze_nugget')
    event.add('forge:storage_blocks/bronze', 'create_dd:bronze_block')

    event.add('minecraft:soul_fire_base_blocks', 'byg:warped_soul_sand')
    event.add('minecraft:soul_fire_base_blocks', 'byg:warped_soul_soil')

    event.add('minecraft:music_discs', 'supplementaries:pancake')
    event.add('minecraft:music_discs', 'wandering_bags:out_of_them_disc')

    event.add('botanicalmachinery:mechanical_apothecary_catalysts', 'paper')
    event.add('botanicalmachinery:mechanical_apothecary_catalysts', 'botania:mana_powder')
    event.add('botanicalmachinery:mechanical_apothecary_catalysts', 'botania:mana_diamond')
    event.add('botanicalmachinery:mechanical_apothecary_catalysts', 'botania:dragonstone')

    event.add('dar:soul_items', 'art_of_forging:dragon_soul')
    event.add('dar:soul_items', 'art_of_forging:soul_ember')
    event.add('dar:soul_items', 'blue_skies:soul_fragment')
    event.add('dar:soul_items', 'botania:life_essence')
    event.add('dar:soul_items', 'quark:soul_bead')
    event.add('dar:soul_items', 'silentgems:soul_gem')

    event.add('dar:spawn_eggs', /spawn_egg/)

    event.add('dar:runes_of_sin', 'botania:rune_envy')
    event.add('dar:runes_of_sin', 'botania:rune_gluttony')
    event.add('dar:runes_of_sin', 'botania:rune_greed')
    event.add('dar:runes_of_sin', 'botania:rune_lust')
    event.add('dar:runes_of_sin', 'botania:rune_pride')
    event.add('dar:runes_of_sin', 'botania:rune_sloth')
    event.add('dar:runes_of_sin', 'botania:rune_wrath')

    event.add('minecraft:music_discs', 'alexsmobs:music_disc_daze')
    event.add('minecraft:music_discs', 'alexsmobs:music_disc_thime')
    event.add('minecraft:music_discs', 'idas:music_disc_calidum')
    event.add('minecraft:music_discs', 'idas:music_disc_slither')
    event.add('minecraft:music_discs', 'integrated_stronghold:music_disc_forlorn')
    event.add('minecraft:music_discs', 'integrated_stronghold:music_disc_sight')

    event.add('forge:coins/brass', 'createdeco:brass_coin')
    event.add('forge:coins/cast_iron', 'createdeco:cast_iron_coin')
    event.add('forge:coins/copper', 'createdeco:copper_coin')
    event.add('forge:coins/copper', 'lightmanscurrency:coin_chocolate_copper')
    event.add('forge:coins/copper', 'lightmanscurrency:coin_copper')
    event.add('forge:coins/diamond', 'lightmanscurrency:coin_chocolate_diamond')
    event.add('forge:coins/diamond', 'lightmanscurrency:coin_diamond')
    event.add('forge:coins/emerald', 'lightmanscurrency:coin_chocolate_emerald')
    event.add('forge:coins/emerald', 'lightmanscurrency:coin_emerald')
    event.add('forge:coins/gold', 'createdeco:gold_coin')
    event.add('forge:coins/gold', 'lightmanscurrency:coin_chocolate_gold')
    event.add('forge:coins/gold', 'lightmanscurrency:coin_gold')
    event.add('forge:coins/iron', 'createdeco:iron_coin')
    event.add('forge:coins/iron', 'lightmanscurrency:coin_chocolate_iron')
    event.add('forge:coins/iron', 'lightmanscurrency:coin_iron')
    event.add('forge:coins/netherite', 'createdeco:netherite_coin')
    event.add('forge:coins/netherite', 'lightmanscurrency:coin_chocolate_netherite')
    event.add('forge:coins/netherite', 'lightmanscurrency:coin_netherite')
    event.add('forge:coins/zinc', 'createdeco:zinc_coin')

    event.add('forge:coins', '#forge:coins/brass')
    event.add('forge:coins', '#forge:coins/cast_iron')
    event.add('forge:coins', '#forge:coins/diamond')
    event.add('forge:coins', '#forge:coins/emerald')
    event.add('forge:coins', '#forge:coins/zinc')

    event.add('forge:seeds', 'byg:white_puffball_spores')
    event.add('forge:seeds', 'culturaldelights:corn_kernels')
    event.add('forge:seeds', 'culturaldelights:cucumber_seeds')
    event.add('forge:seeds', 'culturaldelights:eggplant_seeds')

    event.add('forge:buckets', /_bucket/)

    event.add('forge:mob_buckets', /tadpole_bucket/)
    event.add('forge:mob_buckets', /cod_bucket/)
    event.add('forge:mob_buckets', /salmon_bucket/)
    event.add('forge:mob_buckets', /pufferfish_bucket/)
    event.add('forge:mob_buckets', /tropical_fish_bucket/)
    event.add('forge:mob_buckets', /axolotl_bucket/)
    event.add('forge:mob_buckets', /aerglow_fish_bucket/)
    event.add('forge:mob_buckets', /drifter_bucket/)
    event.add('forge:mob_buckets', /grittle_flatfish_bucket/)
    event.add('forge:mob_buckets', /municipal_monkfish_bucket/)
    event.add('forge:mob_buckets', /charscale_moki_bucket/)
    event.add('forge:mob_buckets', /horizofin_tunid_bucket/)
    event.add('forge:mob_buckets', /alexsmobs:.*_bucket/)
    event.add('forge:mob_buckets', /quark:.*_bucket/)
    event.add('forge:mob_buckets', /unusualend:.*_bucket/)
    event.add('forge:mob_buckets', /byg:.*_bucket/)
    event.add('forge:mob_buckets', 'undergarden:gwibling_bucket')

    event.remove('forge:buckets', '#forge:mob_buckets')

    event.add('create:upright_on_belt', '#forge:buckets')

    event.add('create:layered_casing', 'create:railway_casing')
    event.add('create:layered_casing', 'create_dd:hydraulic_casing')
    event.add('create:layered_casing', 'create_dd:industrial_casing')
    event.add('create:layered_casing', 'create_dd:overburden_casing')
})

ServerEvents.tags('block', event => {

    event.add('minecraft:small_flowers', 'culturaldelights:wild_corn')
    event.add('minecraft:small_flowers', 'culturaldelights:wild_cucumbers')
    event.add('minecraft:small_flowers', 'culturaldelights:wild_eggplants')
    event.add('minecraft:small_flowers', 'farmersrespite:wild_tea_bush')
    event.add('minecraft:small_flowers', 'farmersrespite:wild_coffee_bush')

    event.add('farmersdelight:wild_crop', 'culturaldelights:wild_corn')
    event.add('farmersdelight:wild_crop', 'culturaldelights:wild_cucumbers')
    event.add('farmersdelight:wild_crop', 'culturaldelights:wild_eggplants')
    event.add('farmersdelight:wild_crop', 'farmersrespite:wild_tea_bush')
    event.add('farmersdelight:wild_crop', 'farmersrespite:wild_coffee_bush')

    event.add('minecraft:mineable/pickaxe', 'cfm:post_box')

    event.add('minecraft:climbable', 'everycomp:cfm/byg/ebony_blinds')

    event.add('forge:storage_blocks/silver', 'silentgems:silver_block')
    event.add('forge:storage_blocks/flint', 'cyclic:flint_block')
    event.add('forge:storage_blocks/flint', 'supplementaries:flint_block')
    event.add('forge:storage_block', '#forge:storage_blocks/flint')
})

ServerEvents.tags('entity_type', event => {

    event.add('mob_grinding_utils:no_dirt_spawn', 'mutantmonsters:mutant_creeper')
    event.add('mob_grinding_utils:no_dirt_spawn', 'mutantmonsters:mutant_enderman')
    event.add('mob_grinding_utils:no_dirt_spawn', 'mutantmonsters:mutant_skeleton')
    event.add('mob_grinding_utils:no_dirt_spawn', 'alexsmobs:farseer')

})