
[general]
	#If the player mobs should be able to open doors.
	"Open Doors" = true
	#If true the player mobs will attack all players
	#If false they will ignore players with the same name as themself
	"Attack Twin" = true
	#The difficulty and above that player mobs can open doors, if enabled above.
	#Allowed Values: PEACEFUL, EASY, NORMAL, HARD
	"Open Doors Difficulty" = "PEACEFUL"
	#The chance of players dropping a head with their texture.
	#Set to -1 to disable.
	#Range: -1.0 ~ 1.0
	"Player Head Drop Chance" = 1.0
	#The chance of player mobs dropping their head.
	#Set to -1 to disable.
	#Range: -1.0 ~ 1.0
	"Mob Head Drop Chance" = 1.0
	#The chance of the mob getting the ability to pickup items, it's used on mob spawn.
	#Set to -1 to disable.
	#Range: -1.0 ~ 256.0
	"Pickup Item Chance" = 256.0

#Configs related to spawning the mobs
[spawning]
	#Chance that a player mob will spawn as a baby.
	#Set to -1 to disable.
	#Range: -1.0 ~ 1.0
	"Baby Spawn Chance" = -1.0
	#The id of the dimensions to block spawning in.
	#The player mobs spawn where Zombies spawn, so no need to block dimensions that doesn't contain Zombies.
	#Example id: "minecraft:overworld"
	"Dimension Blocklist" = []
	#What item to be able to spawn in the offhand
	#Offhand items can only spawn when on hard difficulty
	#It won't spawn an item in the offhand if it spawns with a bow like item.
	#There is a separated chance to spawn with an item at all, this is to pick what it to spawn when it does
	#Syntax is "namespace:id-weight"
	"Spawn Items Offhand" = ["minecraft:shield-1", "minecraft:air-4"]
	#A list of items that the player mobs can spawn with.
	#Default is 40% for a bow, 10% for a crossbow and 50% for a sword, then the swords are distributed after that.
	#There is a separated chance to spawn with an item at all, this is to pick what to spawn when it does
	#Syntax is "namespace:id-weight"
	"Spawn Items" = ["minecraft:bow-90", "minecraft:crossbow-10", "minecraft:stone_sword-64", "minecraft:iron_sword-20", "minecraft:golden_sword-10", "minecraft:diamond_sword-5", "minecraft:netherite_sword-1"]
	#Force the mobs to spawn holding items.
	"Force Items Spawn" = false
	#The difficulty and above that player mobs can spawn with items in their offhand.
	#Allowed Values: PEACEFUL, EASY, NORMAL, HARD
	"Offhand Spawn Difficulty" = "HARD"
	#The chance of items spawning in the offhand
	#If holding a projectile weapon this can spawn a tipped arrow if allowed
	#Else it will spawn from the offhand item list
	#Set to -1 to disable.
	#Range: -1.0 ~ 1.0
	"Offhand Spawn Chance" = 0.5
	#Allow for a change to spawn a random tipped arrow when the mob is holding a projectile weapon
	"Spawn Tipped Arrows" = true
	#A list of potion "namespace:id" to block from getting applied to tipped arrows
	"Tipped Arrow Blocklist" = ["minecraft:awkward", "minecraft:empty", "minecraft:fire_resistance", "minecraft:healing", "minecraft:invisibility", "minecraft:leaping", "minecraft:long_fire_resistance", "minecraft:long_invisibility", "minecraft:long_leaping", "minecraft:long_night_vision", "minecraft:long_regeneration", "minecraft:long_strength", "minecraft:long_swiftness", "minecraft:long_turtle_master", "minecraft:long_water_breathing", "minecraft:luck", "minecraft:mundane", "minecraft:night_vision", "minecraft:regeneration", "minecraft:strength", "minecraft:strong_healing", "minecraft:strong_leaping", "minecraft:strong_regeneration", "minecraft:strong_strength", "minecraft:strong_swiftness", "minecraft:strong_turtle_master", "minecraft:swiftness", "minecraft:thick", "minecraft:turtle_master", "minecraft:water"]

#Configs related to the names of the mobs.
[names]
	#A list of names that the player mobs can have.
	"Mob Names" = ["ATG21", "Amy_Night", "AntVenom", "Aphmau", "AxelTheModder", "Baablu", "BdoubleO100", "Bob_Ross", "Boosfer", "Brokemboy", "C418", "CaptainSparklez", "ChaosDog", "ChosenArchitect", "CringyGull", "DanTDM", "Dartron", "Dejojotheawsome", "DemonitizedBoi", "Derpface66", "DestinyPurple", "Dinnerbone", "DoniBobes", "DragonSoda_", "Dream", "ElectroniCritic", "Elmo", "Etho", "EvilXisuma", "FatMemeGod", "FishyBoopkins", "Fundy", "Garfield_", "GeminiTay", "GeorgeNotFound", "Gh05tF1yy", "GhostFly64", "GoodTimeWithScar", "Graser10", "Grian", "Grover_", "Grumm", "Hauntedpasta1", "Henzoid", "HumanCleo", "Huskymudkipz", "Itachi", "ItsFundy", "Its_Dev_", "Jak", "JessTheAxolotl", "JimmyHere", "Jon_Arbuckle_", "KamiyaMidori", "KashiiKiwii", "Keralis1", "Kierrrr", "Kiply", "Knarfy", "LDShadowLady", "LadyAgnes", "Legundo", "Ligeriscool", "Lightman314", "LoadedG789GGMate", "Logdotzip", "LoveTechy", "Luffy", "Luke_TheNotable", "Lynixity", "MECEYECE", "MHF_Herobrine", "MHF_MushroomCow", "MIGimmy", "MrBeardstone", "MrBlaza_", "MrCrayfish", "MrJagsterS", "Mumbo", "MumboJumbo", "MurderMittens5TV", "Mysticpasta1", "Natsu___", "NetherNoah777", "OracleHisty", "OscarGrouch", "PM7John", "Paimon", "Penguiniie", "PerfectBidoof", "PerryThePlatypus", "Ph1LzA", "PhoenixSC", "ProjektButt", "PuffingFishHQ", "Purplecliffe", "Qndres", "Queen_Aliza", "RagePlaysGames", "Ranboo", "Raven_Conspirac3", "RentheKing", "Renthedog", "Rocket", "RosiePies_", "RoyalGhostmit", "SB737", "Safwan", "SairuNai", "Sasuke", "Scooby_", "SillviaTV", "SkythekidRS", "Smallishbeans", "SolidarityGaming", "Sonic", "SpicySaint", "Tango", "TangoCam", "TbhHonest", "Technoblade", "ThatOneBlueGuyYT", "ThatOneRedGuyYT", "TheInfamousQuiff", "TheRealSquiddo", "TheWolfAndTheBoy", "The_Cat_of_Cats", "Threefold", "TommyInnit", "Tubbo_", "TubeAndKnuckle", "TwoMuchGrian", "Vazkii", "Waluigi", "Waterpicker", "WestTheBean", "Wisp", "Writer_Mel", "Xisuma", "Xisumatwo", "YelloWool", "Zambun", "ZedCam", "Zedaph", "ZombieCleo", "_Bender", "_Blanc_", "_Erza_", "_Sans_", "__Laff", "_naruto", "_nep__", "_shadowapples", "_shaggy", "b_ART_ek", "bhami", "billyp673", "bionicLMAO", "bubbo2000", "cjosie1", "deadmau5", "doctor4t", "foxynotail", "hypnotizd", "isGall85", "iskall85", "itsCraftee", "jeb_", "jschlatt", "kevdevz", "lequack", "lookomni", "magicalhobo", "marshmallowz0", "mjd7999", "mypenny", "mysticat_", "oxibee", "polartt", "r4tmaid", "rockit14", "syszee", "tamaOwO", "therealSocksfor1", "xisumavoid"]
	#The time interval in minutes when to reload the links (approximately, based on TPS)
	#If set to 0 it will only sync once on load.
	#Range: > 0
	"Reload Interval" = 60
	#A list of links to get names that the player mobs can have.
	#The names need to be separated by a newline.
	#Names from these links are combined with the named from below
	#As an example you have Twitch subs in the game by using https://whitelist.gorymoon.se
	"Name Links" = []
	#If the names in the whitelist should be used for the player mobs.
	"Use Whitelist" = true

