account = "chaosdog1"
uuid = "e0685ea5-7046-42a5-a2ba-8ba545af96da"
reauthorize = false
hasGlobalBadges = true
hasChannelBadges = true
chatOn = true
pause = false
botId = "8na8n5aa2bbcmy2cotbodmz2kxv1d3"
botSecret = "vet90f0t2c4j8us03ppzassia5h2wr"
